apiVersion: v1
kind: ConfigMap
metadata:
  name: payment-service-config
  namespace: urban-company
data:
  database.url: "jdbc:postgresql://postgres-payment:5432/payment_service_db"
  redis.host: "redis-service"
  kafka.bootstrap-servers: "kafka-service:9092"
  eureka.url: "http://discovery-service:8761/eureka/"
