apiVersion: v1
kind: ConfigMap
metadata:
  name: user-service-config
  namespace: urban-company
data:
  database.url: "jdbc:postgresql://postgres-user:5432/user_service_db"
  redis.host: "redis-service"
  kafka.bootstrap-servers: "kafka-service:9092"
  eureka.url: "http://discovery-service:8761/eureka/"
