spring:
  application:
    name: AirlineManagementSystem

  datasource:
    url: jdbc:postgresql://localhost:5432/airline
    username: airlineadmin
    password: airlinepassword
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

    kafka:
      bootstrap-servers: localhost:9092
      consumer:
        group-id: airline-group
        auto-offset-reset: earliest
        value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
        properties:
          spring.json.trusted.packages: '*'
      producer:
        value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

server:
  port: 8080

jwt:
  secret: bXlfdmVyeV9zZWNyZXRfamV0X3Rva2VuX3NpZ25pbmdfa2V5MTIzNDU27
  expiration-ms: 86400000 # 1 day
