apiVersion: v1
kind: Service
metadata:
  name: partner-service
  namespace: urban-company
  labels:
    app: partner-service
    tier: backend
spec:
  type: ClusterIP
  selector:
    app: partner-service
  ports:
  - port: 8084
    targetPort: 8084
    protocol: TCP
    name: http
