apiVersion: v1
kind: Secret
metadata:
  name: booking-service-secret
  namespace: urban-company
type: Opaque
stringData:
  database.username: "booking_service"
  database.password: "booking_password"
