apiVersion: v1
kind: Secret
metadata:
  name: catalog-service-secret
  namespace: urban-company
type: Opaque
stringData:
  database.username: "catalog_service"
  database.password: "catalog_password"
