apiVersion: v1
kind: Secret
metadata:
  name: partner-service-secret
  namespace: urban-company
type: Opaque
stringData:
  database.username: "partner_service"
  database.password: "partner_password"
